<?php
/**
 * @file
 * migration_demo.features.uuid_file_entity.inc
 */

/**
 * Implements hook_uuid_features_default_file_entities().
 */
function migration_demo_uuid_features_default_file_entities() {
  $files = array();

  $files[] = array(
    'filename' => 'looperman-l-2432827-0125468-polimar-e-scrape.wav',
    'uri' => 'public://looperman-l-2432827-0125468-polimar-e-scrape.wav',
    'filemime' => 'audio/x-wav',
    'filesize' => 655288,
    'status' => 1,
    'type' => 'audio',
    'uuid' => '0274ddc4-3243-4d9d-9704-485280f550aa',
    'rdf_mapping' => array(),
    'metadata' => array(),
    'uuid_features_packaged_file_path' => 'assets/looperman-l-2432827-0125468-polimar-e-scrape.wav',
    'user_uuid' => '9a1e1fa2-7f67-4b7e-be13-7506812ce50f',
  );
  $files[] = array(
    'filename' => 'galapagos-land-iguana.jpg',
    'uri' => 'public://galapagos-land-iguana.jpg',
    'filemime' => 'image/jpeg',
    'filesize' => 3872272,
    'status' => 1,
    'type' => 'image',
    'uuid' => '0df8fa35-ed15-460c-8162-56d2db9c1561',
    'field_file_image_alt_text' => array(),
    'field_file_image_title_text' => array(),
    'rdf_mapping' => array(),
    'metadata' => array(
      'height' => 1956,
      'width' => 2708,
    ),
    'height' => 1956,
    'width' => 2708,
    'uuid_features_packaged_file_path' => 'assets/galapagos-land-iguana.jpg',
    'user_uuid' => '9a1e1fa2-7f67-4b7e-be13-7506812ce50f',
  );
  $files[] = array(
    'filename' => '16003176782_f0020dff2c_z.jpg',
    'uri' => 'public://16003176782_f0020dff2c_z.jpg',
    'filemime' => 'image/jpeg',
    'filesize' => 89649,
    'status' => 1,
    'type' => 'image',
    'uuid' => '19d4facb-f8b8-4484-b041-e08c4e62612b',
    'field_file_image_alt_text' => array(),
    'field_file_image_title_text' => array(),
    'rdf_mapping' => array(),
    'metadata' => array(
      'height' => 419,
      'width' => 640,
    ),
    'height' => 419,
    'width' => 640,
    'uuid_features_packaged_file_path' => 'assets/16003176782_f0020dff2c_z.jpg',
    'user_uuid' => '9a1e1fa2-7f67-4b7e-be13-7506812ce50f',
  );
  $files[] = array(
    'filename' => 'looperman-l-0676809-0118951-vwdubber-mtpowerdrum-doomblackmetal.wav',
    'uri' => 'public://looperman-l-0676809-0118951-vwdubber-mtpowerdrum-doomblackmetal.wav',
    'filemime' => 'audio/x-wav',
    'filesize' => 1737038,
    'status' => 1,
    'type' => 'audio',
    'uuid' => '1b7df139-796b-4446-aeab-867ce8d229b3',
    'rdf_mapping' => array(),
    'metadata' => array(),
    'uuid_features_packaged_file_path' => 'assets/looperman-l-0676809-0118951-vwdubber-mtpowerdrum-doomblackmetal.wav',
    'user_uuid' => '9a1e1fa2-7f67-4b7e-be13-7506812ce50f',
  );
  $files[] = array(
    'filename' => 'rock-agama.jpg',
    'uri' => 'public://rock-agama.jpg',
    'filemime' => 'image/jpeg',
    'filesize' => 712025,
    'status' => 1,
    'type' => 'image',
    'uuid' => '1d890f89-302d-4aea-8472-41fc1b2b1d31',
    'field_file_image_alt_text' => array(),
    'field_file_image_title_text' => array(),
    'rdf_mapping' => array(),
    'metadata' => array(
      'height' => 1500,
      'width' => 2000,
    ),
    'height' => 1500,
    'width' => 2000,
    'uuid_features_packaged_file_path' => 'assets/rock-agama.jpg',
    'user_uuid' => '9a1e1fa2-7f67-4b7e-be13-7506812ce50f',
  );
  $files[] = array(
    'filename' => 'Thorny_devil_pale.jpg',
    'uri' => 'public://Thorny_devil_pale.jpg',
    'filemime' => 'image/jpeg',
    'filesize' => 568155,
    'status' => 1,
    'type' => 'image',
    'uuid' => '23ed9d19-6683-43c8-8ee4-f1af233748b3',
    'field_file_image_alt_text' => array(),
    'field_file_image_title_text' => array(),
    'rdf_mapping' => array(),
    'metadata' => array(
      'height' => 1447,
      'width' => 1920,
    ),
    'height' => 1447,
    'width' => 1920,
    'uuid_features_packaged_file_path' => 'assets/Thorny_devil_pale.jpg',
    'user_uuid' => '9a1e1fa2-7f67-4b7e-be13-7506812ce50f',
  );
  $files[] = array(
    'filename' => 'looperman-l-0671112-0093021-danke-corroded-guitars-2.wav',
    'uri' => 'public://looperman-l-0671112-0093021-danke-corroded-guitars-2.wav',
    'filemime' => 'audio/x-wav',
    'filesize' => 3763248,
    'status' => 1,
    'type' => 'audio',
    'uuid' => '2710990f-c80f-4977-b279-4d29bb7d8c2b',
    'rdf_mapping' => array(),
    'metadata' => array(),
    'uuid_features_packaged_file_path' => 'assets/looperman-l-0671112-0093021-danke-corroded-guitars-2.wav',
    'user_uuid' => '9a1e1fa2-7f67-4b7e-be13-7506812ce50f',
  );
  $files[] = array(
    'filename' => 'Cordylus_giganteus.jpg',
    'uri' => 'public://Cordylus_giganteus.jpg',
    'filemime' => 'image/jpeg',
    'filesize' => 343654,
    'status' => 1,
    'type' => 'image',
    'uuid' => '35445c82-a660-401c-b759-d1fcf8964e37',
    'field_file_image_alt_text' => array(),
    'field_file_image_title_text' => array(),
    'rdf_mapping' => array(),
    'metadata' => array(
      'height' => 593,
      'width' => 790,
    ),
    'height' => 593,
    'width' => 790,
    'uuid_features_packaged_file_path' => 'assets/Cordylus_giganteus.jpg',
    'user_uuid' => '9a1e1fa2-7f67-4b7e-be13-7506812ce50f',
  );
  $files[] = array(
    'filename' => 'looperman-l-2615019-0129831-bass-bug.wav',
    'uri' => 'public://looperman-l-2615019-0129831-bass-bug.wav',
    'filemime' => 'audio/x-wav',
    'filesize' => 940844,
    'status' => 1,
    'type' => 'audio',
    'uuid' => '4d65796c-b840-4b08-b925-a58c8ac9d76a',
    'rdf_mapping' => array(),
    'metadata' => array(),
    'uuid_features_packaged_file_path' => 'assets/looperman-l-2615019-0129831-bass-bug.wav',
    'user_uuid' => '9a1e1fa2-7f67-4b7e-be13-7506812ce50f',
  );
  $files[] = array(
    'filename' => 'looperman-l-0630386-0100089-josephfunk-metal-talk-rhythm-guitar-w-fxs-130 (1).wav',
    'uri' => 'public://looperman-l-0630386-0100089-josephfunk-metal-talk-rhythm-guitar-w-fxs-130 (1).wav',
    'filemime' => 'audio/x-wav',
    'filesize' => 5210712,
    'status' => 1,
    'type' => 'audio',
    'uuid' => '5d907155-a064-4f58-ad7a-d17fb7605681',
    'rdf_mapping' => array(),
    'metadata' => array(),
    'uuid_features_packaged_file_path' => 'assets/looperman-l-0630386-0100089-josephfunk-metal-talk-rhythm-guitar-w-fxs-130 (1).wav',
    'user_uuid' => '9a1e1fa2-7f67-4b7e-be13-7506812ce50f',
  );
  $files[] = array(
    'filename' => 'looperman-l-1414881-0081908-epicrecord-heavy-electric-1.wav',
    'uri' => 'public://looperman-l-1414881-0081908-epicrecord-heavy-electric-1.wav',
    'filemime' => 'audio/x-wav',
    'filesize' => 1059556,
    'status' => 1,
    'type' => 'audio',
    'uuid' => '632b911b-0d2f-4d58-abce-fdb2b50a22f8',
    'rdf_mapping' => array(),
    'metadata' => array(),
    'uuid_features_packaged_file_path' => 'assets/looperman-l-1414881-0081908-epicrecord-heavy-electric-1.wav',
    'user_uuid' => '9a1e1fa2-7f67-4b7e-be13-7506812ce50f',
  );
  $files[] = array(
    'filename' => '1280px-Marineiguanas.JPG',
    'uri' => 'public://1280px-Marineiguanas.JPG',
    'filemime' => 'image/jpeg',
    'filesize' => 324733,
    'status' => 1,
    'type' => 'image',
    'uuid' => '9ce71b7f-f1f2-4857-a5a2-fbe48693af38',
    'field_file_image_alt_text' => array(),
    'field_file_image_title_text' => array(),
    'rdf_mapping' => array(),
    'metadata' => array(
      'height' => 853,
      'width' => 1280,
    ),
    'height' => 853,
    'width' => 1280,
    'uuid_features_packaged_file_path' => 'assets/1280px-Marineiguanas.JPG',
    'user_uuid' => '9a1e1fa2-7f67-4b7e-be13-7506812ce50f',
  );
  $files[] = array(
    'filename' => 'Frill-necked_Lizard_(Chlamydosaurus_kingii)_(8692622586).jpg',
    'uri' => 'public://Frill-necked_Lizard_(Chlamydosaurus_kingii)_(8692622586).jpg',
    'filemime' => 'image/jpeg',
    'filesize' => 374722,
    'status' => 1,
    'type' => 'image',
    'uuid' => 'ca42a6b9-99c3-4171-942d-abd9ecef4481',
    'field_file_image_alt_text' => array(),
    'field_file_image_title_text' => array(),
    'rdf_mapping' => array(),
    'metadata' => array(
      'height' => 853,
      'width' => 1280,
    ),
    'height' => 853,
    'width' => 1280,
    'uuid_features_packaged_file_path' => 'assets/Frill-necked_Lizard_(Chlamydosaurus_kingii)_(8692622586).jpg',
    'user_uuid' => '9a1e1fa2-7f67-4b7e-be13-7506812ce50f',
  );
  $files[] = array(
    'filename' => '30217984_Unknown.jpg',
    'uri' => 'public://30217984_Unknown.jpg',
    'filemime' => 'image/jpeg',
    'filesize' => 1121890,
    'status' => 1,
    'type' => 'image',
    'uuid' => 'f6b64896-b001-4137-8d22-9918a248133e',
    'field_file_image_alt_text' => array(),
    'field_file_image_title_text' => array(),
    'rdf_mapping' => array(),
    'metadata' => array(
      'height' => 1536,
      'width' => 2048,
    ),
    'height' => 1536,
    'width' => 2048,
    'uuid_features_packaged_file_path' => 'assets/30217984_Unknown.jpg',
    'user_uuid' => '9a1e1fa2-7f67-4b7e-be13-7506812ce50f',
  );
  return $files;
}
